version: '3.8'

services:

  web:
    build: .
    env_file:
      - .env
    environment:
      db_dsn: "postgresql+asyncpg://postgres:password@db:5433/postgres"
      redis_host: "redis"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - db_migration

  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"  # Use the Redis port from the .env file
    volumes:
      - ./redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  db:
    image: postgres:17.0-alpine3.20
    hostname: db
    expose:
      - "5433" # Publishes 5431 to other containers but NOT to host machine
    ports:
      - "5433:5433"  # unwanted conflict with database in main pc
    command: -p 5433
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -h localhost -p 5433" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db_migration:
    build:
      dockerfile: ./Dockerfile
    restart: "on-failure"
    environment:
      db_dsn: "postgresql+asyncpg://postgres:password@db:5433/postgres"
    depends_on:
      - db
    env_file: .env
    command: >
      sh -c "poetry run alembic upgrade head"
