version: '3.8'

services:

  web:
    build: .
    env_file:
      - .env
    environment:
      db_dsn: "postgresql://postgres:password@db:5433/postgres"
      redis_host: "redis"

    ports:
      - "8000:8000"

    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"  # Use the Redis port from the .env file
    volumes:
      - ./redis-data:/data

  db:
    image: postgres:11.5-alpine
    hostname: db
    expose:
      - "5433" # Publishes 5431 to other containers but NOT to host machine
    ports:
      - "5433:5433"  # unwanted conflict with database in main pc
    command: -p 5433
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached
