version: '3'

services:

  web:
    build: .
    env_file:
      - .env
    environment:
      db_dsn: "postgresql://postgres:password@db:5433/postgres"
      redis_dsn: "amqp://user:password@rabbitmq/"
    depends_on:
      - db
      - rabbit

  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"  # Use the Redis port from the .env file
    volumes:
      - redis-data:/data

  db:
    image: postgres:11.5-alpine
    hostname: db
    expose:
      - "5433" # Publishes 5431 to other containers but NOT to host machine
    ports:
      - "5433:5433"  # unwanted conflict with database in main pc
    command: -p 5433
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached

  rabbit:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always

    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 524288
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    expose:
      - "15672"
      - "5672"
