"""added is_selected

Revision ID: a0fd3f38c759
Revises: ca67e38d40cf
Create Date: 2024-10-03 09:21:55.903327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0fd3f38c759'
down_revision: Union[str, None] = 'ca67e38d40cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('is_selected', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tokens', 'is_selected')
    # ### end Alembic commands ###
