"""huh2

Revision ID: ca67e38d40cf
Revises: fa7af80925a1
Create Date: 2024-10-02 22:14:51.913821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca67e38d40cf'
down_revision: Union[str, None] = 'fa7af80925a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonuses', sa.Column('bonus', sa.Integer(), server_default='0', nullable=False))
    op.add_column('bonuses', sa.Column('activated_for', sa.String(length=255), nullable=True))
    op.add_column('bonuses', sa.Column('completed_tasks', sa.JSON(), server_default='[]', nullable=True))
    op.alter_column('bonuses', 'roblox_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_bonuses_id', table_name='bonuses')
    op.drop_constraint('uq_bonuses_token', 'bonuses', type_='unique')
    op.drop_column('bonuses', 'id')
    op.drop_column('bonuses', 'token')
    op.drop_column('bonuses', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonuses', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('bonuses', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('bonuses', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.create_unique_constraint('uq_bonuses_token', 'bonuses', ['token'])
    op.create_index('ix_bonuses_id', 'bonuses', ['id'], unique=False)
    op.alter_column('bonuses', 'roblox_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('bonuses', 'completed_tasks')
    op.drop_column('bonuses', 'activated_for')
    op.drop_column('bonuses', 'bonus')
    # ### end Alembic commands ###
