"""huh

Revision ID: fa7af80925a1
Revises: d827b9930ab4
Create Date: 2024-10-02 22:05:22.187339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7af80925a1'
down_revision: Union[str, None] = 'd827b9930ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonuses',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('roblox_name', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bonuses')),
    sa.UniqueConstraint('token', name=op.f('uq_bonuses_token'))
    )
    op.create_index(op.f('ix_bonuses_id'), 'bonuses', ['id'], unique=False)
    op.alter_column('user_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint(op.f('uq_user_tokens_token'), 'user_tokens', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_tokens_token'), 'user_tokens', type_='unique')
    op.alter_column('user_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_bonuses_id'), table_name='bonuses')
    op.drop_table('bonuses')
    # ### end Alembic commands ###
